# Generación de Coordenadas

test

## Selección de Localidades

In [1]:
import geopandas as gpd
import pandas as pd

In [3]:
# source: https://www.geogpsperu.com/2014/03/base-de-datos-peru-shapefile-shp-minam.html
shp_path = r"data\Distrital INEI 2023 geogpsperu SuyoPomalia\Distrital INEI 2023 geogpsperu SuyoPomalia.shp"
peru = gpd.read_file(shp_path)

In [ ]:
# filtramos por 4 ciudades ejemplo.
lista_departamentos = ["LIMA", "AREQUIPA", "ICA", "CUSCO"]
departamentos = peru[peru["DEPARTAMEN"].isin(lista_departamentos)]

Vamos a elegir los distritos de cada departamento con mayor poblacion

DISTRITOS:
- AREQUIPA: AREQUIPA, ALTO SELVA ALEGRE, CAYMA, CERRO COLORADO
- ICA:: ICA, PARCONA, CHINCHA ALTA
- CUSCO: CUSCO, SANTIAGO, WANCHAQ, SAN SEBASTIAN
- LIMA:

In [72]:
lista_distritos = [
    "AREQUIPA",
    "ALTO SELVA ALEGRE",
    "CAYMA",
    "CERRO COLORADO",
    "ICA",
    "PARCONA",
    "CHINCHA ALTA",
    "CUSCO",
    "SANTIAGO",
    "WANCHAQ",
    "SAN SEBASTIAN",
    "LIMA",
    "ANCON",
    "ATE",
    "BARRANCO",
    "BREÑA",
    "COMAS",
    "INDEPENDENCIA",
    "JESUS MARIA",
    "LA MOLINA",
    "LA VICTORIA",
    "LINCE",
    "LOS OLIVOS",
    "PUEBLO LIBRE",
    "MIRAFLORES",
    "SAN BORJA",
    "SAN ISIDRO",
    "SANTIAGO DE SURCO",
]
distritos = departamentos[departamentos["DISTRITO"].isin(lista_distritos)]
distritos_lima = distritos[distritos["PROVINCIA"] == "LIMA"]
distritos_lima

,UBIGEO,CCDD,CCPP,CCDI,DEPARTAMEN,PROVINCIA,DISTRITO,OBJECTID,ESRI_OID,geometry
1293,150101,15,01,01,LIMA,LIMA,LIMA,1294.0,1294.0,"POLYGON ((-77.00972 -12.03083, -77.00921 -12.0..."
1294,150102,15,01,02,LIMA,LIMA,ANCON,1295.0,1295.0,"POLYGON ((-77.06652 -11.57251, -77.06614 -11.5..."
1295,150103,15,01,03,LIMA,LIMA,ATE,1296.0,1296.0,"POLYGON ((-76.83689 -11.9937, -76.83517 -11.99..."
1296,150104,15,01,04,LIMA,LIMA,BARRANCO,1297.0,1297.0,"POLYGON ((-77.01948 -12.13061, -77.01933 -12.1..."
1297,150105,15,01,05,LIMA,LIMA,BREÑA,1298.0,1298.0,"POLYGON ((-77.05335 -12.04917, -77.05332 -12.0..."
1302,150110,15,01,10,LIMA,LIMA,COMAS,1303.0,1303.0,"POLYGON ((-77.05095 -11.88781, -77.04998 -11.8..."
1304,150112,15,01,12,LIMA,LIMA,INDEPENDENCIA,1305.0,1305.0,"POLYGON ((-77.02872 -11.96252, -77.02872 -11.9..."
1305,150113,15,01,13,LIMA,LIMA,JESUS MARIA,1306.0,1306.0,"POLYGON ((-77.03762 -12.06447, -77.0378 -12.06..."
1306,150114,15,01,14,LIMA,LIMA,LA MOLINA,1307.0,1307.0,"POLYGON ((-76.94449 -12.05684, -76.9441 -12.05..."
1307,150115,15,01,15,LIMA,LIMA,LA VICTORIA,1308.0,1308.0,"POLYGON ((-77.01729 -12.05793, -77.01716 -12.0..."
1308,150116,15,01,16,LIMA,LIMA,LINCE,1309.0,1309.0,"POLYGON ((-77.02807 -12.07871, -77.02805 -12.0..."
1309,150117,15,01,17,LIMA,LIMA,LOS OLIVOS,1310.0,1310.0,"POLYGON ((-77.07364 -11.91778, -77.07335 -11.9..."
1313,150121,15,01,21,LIMA,LIMA,PUEBLO LIBRE,1314.0,1314.0,"POLYGON ((-77.05433 -12.06659, -77.05431 -12.0..."
1314,150122,15,01,22,LIMA,LIMA,MIRAFLORES,1315.0,1315.0,"POLYGON ((-77.02739 -12.10328, -77.02741 -12.1..."
1322,150130,15,01,30,LIMA,LIMA,SAN BORJA,1323.0,1323.0,"POLYGON ((-76.9872 -12.08007, -76.98711 -12.08..."
1323,150131,15,01,31,LIMA,LIMA,SAN ISIDRO,1324.0,1324.0,"POLYGON ((-77.04866 -12.08511, -77.04858 -12.0..."
1332,150140,15,01,40,LIMA,LIMA,SANTIAGO DE SURCO,1333.0,1333.0,"POLYGON ((-76.95961 -12.07575, -76.95938 -12.0..."

## Generacion de puntos

In [43]:
import random
from shapely.geometry import Point

In [45]:
def generar_puntos(localidad, cantidad):
    """funcion para generar puntos en una localidad determinada.
    Se pasa una geometria de ciudad y la cantidad de puntos a generar."""
    puntos = []
    minx, miny, maxx, maxy = localidad.bounds

    while len(puntos) < cantidad:
        p = Point(random.uniform(minx, maxx), random.uniform(miny, maxy))
        if localidad.contains(p):
            puntos.append(p)
    return puntos

In [77]:
puntos_total = []

for _, distrito in distritos_lima.iterrows():
    geom = distrito.geometry
    puntos = generar_puntos(geom, 29)
    puntos_total += [
        {
            "distrito": distrito["DISTRITO"],
            "departamento": distrito["DEPARTAMEN"],
            "geometry": p,
        }
        for p in puntos
    ]

In [78]:
gdf_puntos = gpd.GeoDataFrame(puntos_total, crs="EPSG:4326")
gdf_puntos

              distrito departamento                     geometry
0                 LIMA         LIMA  POINT (-77.00947 -12.05707)
1                 LIMA         LIMA  POINT (-77.08194 -12.03984)
2                 LIMA         LIMA   POINT (-77.0545 -12.04442)
3                 LIMA         LIMA   POINT (-77.06685 -12.0466)
4                 LIMA         LIMA  POINT (-77.03953 -12.06268)
..                 ...          ...                          ...
488  SANTIAGO DE SURCO         LIMA   POINT (-77.00642 -12.1413)
489  SANTIAGO DE SURCO         LIMA  POINT (-76.99853 -12.14501)
490  SANTIAGO DE SURCO         LIMA   POINT (-77.00842 -12.1445)
491  SANTIAGO DE SURCO         LIMA   POINT (-76.98765 -12.1632)
492  SANTIAGO DE SURCO         LIMA   POINT (-76.97453 -12.1259)

[493 rows x 3 columns]

In [102]:
gdf_puntos.loc[0]["geometry"].x

-77.0094710395474

## Reverse Lookup
source: https://nominatim.org/release-docs/develop/api/Overview/

In [79]:
import requests
import time

In [80]:
url_path = "https://nominatim.openstreetmap.org/reverse"
# must complete the path with : ?lat=<value>&lon=<value>&<params>

In [ ]:
# funcion para contactar a la API
def reverse_geocode(lat, lon):
    try:
        url = url_path
        params = {"lat": lat, "lon": lon, "format": "json", "addressdetails": 1}
        headers = {"User-Agent": "geo-bot-test"}
        r = requests.get(url, params=params, headers=headers)
        if r.status_code == 200:
            return r.json().get("display_name", "")
    except Exception as e:
        print(e)
        return None

In [ ]:
# test
lat = gdf_puntos.loc[0]["geometry"].y
lon = gdf_puntos.loc[0]["geometry"].x

address = reverse_geocode(lat, lon)
address

'Jirón Junín, San Cayetano, El Agustino, Lima, Lima Metropolitana, Lima, 15011, Perú'

In [107]:
address_list = []

for idx, row in gdf_puntos.iterrows():
    lon = row.geometry.x
    lat = row.geometry.y
    print(idx, lat, lon)
    address_name = reverse_geocode(lat, lon)
    address_list.append(address_name)
    time.sleep(1)  # es necesario esperar un segundo para evitar ser baneados.

0 -12.05707439737378 -77.0094710395474
1 -12.039835577577 -77.08194357062793
2 -12.044421320274179 -77.05450100720492
3 -12.04659541125291 -77.06684997366185
4 -12.062679211911018 -77.03953130949068
5 -12.045915572203171 -77.02785423864809
6 -12.043696843231688 -77.03694678875438
7 -12.047001088880315 -77.04241794524899
8 -12.046147535614805 -77.01992713704703
9 -12.0548011775825 -77.03111128213486
10 -12.043686095113623 -77.03502671615718
11 -12.045954244491098 -77.03459889276506
12 -12.04524542261205 -77.05290606011482
13 -12.042184169161981 -77.08187349063338
14 -12.066289284634559 -77.06593594595394
15 -12.052355508873168 -77.0208957857248
16 -12.04027169788169 -77.0574648071817
17 -12.03794985047963 -77.0483276137079
18 -12.039534017736932 -77.04598445933658
19 -12.064881550956976 -77.03489411963065
20 -12.03821189040728 -77.06011978055915
21 -12.050743615853168 -77.0351944852473
22 -12.052192966712973 -77.06734161539299
23 -12.056088342554903 -77.06200002087198
24 -12.074725555523397 -77.03157119707083
25 -12.047767437475082 -77.0678103965989
26 -12.041816538453705 -77.03978734704035
27 -12.034788578199892 -77.07364688068184
28 -12.053995383092046 -77.04167596751428
29 -11.62314379417685 -77.07395321213819
30 -11.61419234645878 -77.0223375804894
31 -11.624761637052439 -77.05119318941678
32 -11.650611082635162 -77.12504122740756
33 -11.595483356662939 -77.08082792397865
34 -11.686339074098493 -77.14772387272367
35 -11.76444375518974 -77.16759068088345
36 -11.653835654777959 -77.11220718403477
37 -11.663380549580966 -77.12572256021764
38 -11.777559154925378 -77.0793719310241
39 -11.762788911992693 -77.16517899599168
40 -11.754291322330435 -77.12882838828311
41 -11.650988696965612 -77.12227298603578
42 -11.712400400720405 -77.15006569337552
43 -11.780291393274483 -77.05733044297786
44 -11.57769523938026 -77.05118854175218
45 -11.749067393832394 -77.04066998448916
46 -11.608667429274538 -77.01313499353365
47 -11.7284764239978 -77.12636143799364
48 -11.622899119976998 -77.03575685611747
49 -11.80158925729654 -77.12840726385514
50 -11.71890415993469 -77.12379263818379
51 -11.685627575203739 -77.06960468563646
52 -11.61053672705163 -77.05732180435913
53 -11.712281221147247 -77.14895255706833
54 -11.74438945021776 -77.0790577996646
55 -11.61217826838772 -77.05692735565361
56 -11.667669922555312 -77.07341375174211
57 -11.713733383450041 -77.16169290844657
58 -12.041505979257074 -76.86102425811701
59 -12.060475506276223 -76.95449165695389
60 -12.01832042926552 -76.78863672990937
61 -12.041107019241762 -76.92451531354632
62 -12.038528666695049 -76.90826657675996
63 -12.056959598466232 -76.93843994748414
64 -12.039750939001975 -76.88296286375846
65 -12.03410482882085 -76.86968812939705
66 -12.031281411759018 -76.79936310920354
67 -12.03401693449336 -76.9122514967421
68 -11.99978602169908 -76.82611764420201
69 -12.05314794007889 -76.90172440708601
70 -12.026868862220349 -76.81361949022704
71 -12.032671514544333 -76.9293031114763
72 -12.024584093028672 -76.9411708431376
73 -12.038353270330836 -76.81828971336901
74 -12.059112323833277 -76.90531440534346
75 -12.03349654878997 -76.82305264697624
76 -12.024390870779294 -76.82457940260096
77 -12.006453708909449 -76.8039202105257
78 -12.018083921011135 -76.8163956638617
79 -12.011744953460152 -76.85449837165832
80 -12.048526225370733 -76.90225227465086
81 -12.035169707847517 -76.939980422472
82 -12.040583771392015 -76.82412744526091
83 -12.023781742003957 -76.84829371880333
84 -12.009129525091732 -76.87681194616151
85 -12.076800474104907 -76.98078607475931
86 -12.069790917426388 -76.98687623529973
87 -12.14505136461798 -77.0160433840793
88 -12.139659195000839 -77.02705718200207
89 -12.152273256989034 -77.02196623502282
90 -12.142704904262873 -77.02511686321868
91 -12.149327736050568 -77.0220329714129
92 -12.15267922172674 -77.02446675665871
93 -12.146376120573672 -77.02438533493263
94 -12.1353240204362 -77.02083854470646
95 -12.138901508941403 -77.02394143375247
96 -12.15383283631887 -77.02237137469355
97 -12.142734891767777 -77.02619730975073
98 -12.147382391951323 -77.02270469240358
99 -12.13571757117379 -77.02310665334132
100 -12.145344063193903 -77.01940167046341
101 -12.136147321821388 -77.02188441303119
102 -12.153367503213078 -77.0192468309933
103 -12.137160666089317 -77.02480081767642
104 -12.144158204783862 -77.01401738150021
105 -12.137800295272317 -77.01932086920067
106 -12.149772542164639 -77.02385997489966
107 -12.141061583682701 -77.01550913038058
108 -12.151240240336152 -77.02475598725623
109 -12.14283307731924 -77.02319875923155
110 -12.140030530240177 -77.0230416357669
111 -12.154222333741279 -77.02017399757734
112 -12.141197038175815 -77.01374433785914
113 -12.142967833140684 -77.01827252031218
114 -12.144047550558668 -77.0212999618078
115 -12.141237497701052 -77.01424265249781
116 -12.049449367326226 -77.05188366350117
117 -12.058051240467432 -77.05360710614815
118 -12.05752663809945 -77.05234039271353
119 -12.052404293033856 -77.05420686742842
120 -12.050761763276084 -77.05196342327767
121 -12.057585151379003 -77.05467647594622
122 -12.05299426046612 -77.04940866214928
123 -12.066638968974852 -77.0570874589696
124 -12.062709497586095 -77.05376769271858
125 -12.065894843185514 -77.05558034673666
126 -12.057085297323097 -77.0511729715002
127 -12.066273637375371 -77.05608594263265
128 -12.054944375988105 -77.05524119563768
129 -12.053865093462154 -77.0471442901041
130 -12.061830450679638 -77.05253933880742
131 -12.06268939776295 -77.05577212812409
132 -12.054607801737669 -77.04365048973673
133 -12.053943214593982 -77.05144270273576
134 -12.060678004765945 -77.0432072231222
135 -12.061241495639083 -77.05361971962627
136 -12.06374454518908 -77.05287607594377
137 -12.056875739996512 -77.04952334600085
138 -12.050147110117498 -77.0512613717416
139 -12.06005684227844 -77.04884285333952
140 -12.062480813427937 -77.05637290630231
141 -12.058468821623304 -77.04536934964197
142 -12.055974552540993 -77.05003034671967
143 -12.060951505554577 -77.04605682041282
144 -12.052741697218973 -77.04582991064171
145 -11.938512328040794 -77.03039805027669
146 -11.901722425239466 -77.06437401748173
147 -11.929222497227588 -77.07130075674927
148 -11.90742573764633 -77.01558632807522
149 -11.906444650158537 -76.99501969333859
150 -11.916412468215057 -77.01502741700745
151 -11.913097332425068 -77.01507171569985
152 -11.927645783675759 -77.00456509238332
153 -11.967760111120471 -77.05672213880523
154 -11.93545800529227 -77.06083323000881
155 -11.938020159777537 -77.0698962146865
156 -11.908483852182368 -77.03168627470022
157 -11.933480898940068 -77.02403923387936
158 -11.962440537730222 -77.03649978233975
159 -11.92141414007101 -77.01641705795686
160 -11.92016338062872 -77.01510999679532
161 -11.912620465599966 -77.00792129967205
162 -11.931711861766022 -77.03768188974458
163 -11.952812852552718 -77.03763221400462
164 -11.941720715327143 -77.05783455512801
165 -11.903073320196345 -77.03745296732782
166 -11.922133132122466 -77.01046365013755
167 -11.941794166809967 -77.0175877107273
168 -11.947015083316808 -77.03701299651699
169 -11.896940777517985 -77.04141963870799
170 -11.930105062934809 -77.06391007255154
171 -11.9162768435959 -76.99879569201394
172 -11.952736492702778 -77.05586834297456
173 -11.924593397726102 -77.03461210936838
174 -11.984402304302286 -77.05307908292657
175 -11.988554470339837 -77.04805401277088
176 -12.004082772126404 -77.05757322412323
177 -11.974551061727803 -77.04566243419136
178 -12.010446608367067 -77.04866594350713
179 -11.995809772588608 -77.04491066787571
180 -11.980351370872656 -77.02911740308878
181 -11.994029367504478 -77.0607666366507
182 -11.990741416696475 -77.05412597694722
183 -11.967207839967687 -77.03203351175726
184 -11.995861031124003 -77.05806941688478
185 -11.98244993828801 -77.05277102721806
186 -12.010206177639175 -77.04974604970438
187 -11.993908109875177 -77.05190975334672
188 -11.990184638354394 -77.05655315621217
189 -11.96440799678344 -77.03715853920531
190 -11.991763740376484 -77.0427313937663
191 -11.98541894628724 -77.03753953093886
192 -12.007756364444496 -77.05696091489851
193 -11.993693009799127 -77.05240466046472
194 -11.998347375836522 -77.04327683985338
195 -12.010376107701317 -77.04703879501893
196 -11.985252397573445 -77.05218820689596
197 -11.984304758823779 -77.0364359427781
198 -11.974206742625018 -77.03176493155657
199 -11.992160816744036 -77.05067730400701
200 -11.978089327855146 -77.0408309218756
201 -11.989715564251751 -77.04675830902353
202 -11.998265052131819 -77.05366492913228
203 -12.088717851641578 -77.05295478247714
204 -12.069660464866699 -77.04304959409296
205 -12.081715194228027 -77.0486086010032
206 -12.068036100417695 -77.04106202334196
207 -12.069524791889453 -77.03955024908923
208 -12.079071110057772 -77.04009681958404
209 -12.079503272451271 -77.04076368669062
210 -12.080733321721253 -77.04845113865154
211 -12.07817493449764 -77.0543785826055
212 -12.074289480538821 -77.03971155657227
213 -12.081643955941685 -77.04744690661674
214 -12.084904315140582 -77.05951919337205
215 -12.070140695792224 -77.04964347582505
216 -12.0834519915654 -77.05948560952396
217 -12.081598020892551 -77.04242264923374
218 -12.090056664491978 -77.05453730838354
219 -12.065763603024452 -77.03795142282412
220 -12.086453028384396 -77.05395893199935
221 -12.07759665985456 -77.05482511549667
222 -12.065258073496715 -77.0452382672464
223 -12.072890722816512 -77.05106254826275
224 -12.073324163741288 -77.0375880200968
225 -12.066670393470652 -77.04188483493867
226 -12.07204389824927 -77.04861153654834
227 -12.07746121863586 -77.05133715104485
228 -12.077088410495703 -77.0425409128347
229 -12.086793692833263 -77.05594960075479
230 -12.084797468561568 -77.05992308485355
231 -12.071762054320956 -77.05068706448867
232 -12.116107697762146 -76.92710812959548
233 -12.074324258865593 -76.92965824706229
234 -12.112246834776677 -76.93799086211239
235 -12.08002959065402 -76.91087339068503
236 -12.081024002833251 -76.89144870039765
237 -12.105967757015025 -76.90943944823694
238 -12.063246833268554 -76.95868920293013
239 -12.076468473226026 -76.90113268553962
240 -12.079984100215496 -76.92071653019858
241 -12.089181951076334 -76.95769383234706
242 -12.09924538119004 -76.91444797895439
243 -12.06852374490436 -76.92337169173548
244 -12.110715863475091 -76.92758929588935
245 -12.09943372565558 -76.94328124494105
246 -12.089656333671224 -76.95113969014535
247 -12.076015001546455 -76.90048542367524
248 -12.084978098142193 -76.94622294213413
249 -12.094889388238713 -76.9313170252959
250 -12.07239568764066 -76.93627689422257
251 -12.06966842990897 -76.91030271451825
252 -12.064172405289458 -76.9036240797099
253 -12.116790888256538 -76.91961904771692
254 -12.09504435769734 -76.91348214569402
255 -12.065624339851283 -76.91501754630198
256 -12.118985523652258 -76.94333805841633
257 -12.094872611482431 -76.91068940283077
258 -12.080970746391943 -76.96744782483238
259 -12.07653115079145 -76.88941330484775
260 -12.066425421119979 -76.96123008749507
261 -12.068327695325802 -77.03165759795816
262 -12.06312487917464 -77.01737297563719
263 -12.06535118822519 -77.00180157996206
264 -12.068600525377288 -77.01271270665313
265 -12.070180845804229 -77.02101956320804
266 -12.086034435021695 -77.02410187923874
267 -12.088540415857759 -77.01993372815275
268 -12.083739426137843 -77.02471287811088
269 -12.067933129792918 -77.0041913682672
270 -12.087027163626555 -77.01902034921577
271 -12.071877209506521 -77.01871060598674
272 -12.059210216570447 -77.01661704255936
273 -12.081738130354436 -77.02320909417578
274 -12.0723831710631 -77.01810195221547
275 -12.064716110801635 -77.01643300334294
276 -12.069439566418351 -77.01076629908582
277 -12.06401461824064 -77.01618774731294
278 -12.072424204555961 -77.00365389873312
279 -12.072213809024193 -77.00941175141219
280 -12.073952224039443 -77.00890004679735
281 -12.073990050717615 -77.01702680738279
282 -12.080492744005355 -77.0251798229362
283 -12.066696418374445 -77.02562681022647
284 -12.067596097184818 -77.01679989424113
285 -12.066578649896785 -77.01215114435185
286 -12.071775080552689 -77.02742619126207
287 -12.06526586388546 -77.02935161102327
288 -12.080137642360326 -77.02138462591925
289 -12.07614590010781 -77.0290970485793
290 -12.09089842937682 -77.04601057376782
291 -12.079388541787212 -77.03110982239699
292 -12.081760270677071 -77.03513291801872
293 -12.088253663042257 -77.03878486079154
294 -12.087435741066017 -77.04423967785053
295 -12.078977754439187 -77.02848571988763
296 -12.088038939995853 -77.02903540496025
297 -12.087191065012034 -77.02904141761734
298 -12.08309840356623 -77.02682087093666
299 -12.082042578382845 -77.03716459893799
300 -12.088231636013687 -77.04625611735587
301 -12.090324105554867 -77.0462866418967
302 -12.0883550034411 -77.04651288558608
303 -12.084205917056854 -77.04579126783145
304 -12.082536459141663 -77.0331470604032
305 -12.083902502803339 -77.02857821752733
306 -12.086451508642636 -77.04022065036109
307 -12.089588585375834 -77.02892403452059
308 -12.088736390964602 -77.04644171066924
309 -12.082779963429113 -77.03331894209333
310 -12.080916272387688 -77.03495856915762
311 -12.085079165221469 -77.0482590943205
312 -12.082638076523043 -77.03964507901333
313 -12.081761464497784 -77.02944145642108
314 -12.09150587755252 -77.02806288598242
315 -12.081205739138756 -77.03682095463323
316 -12.091192961774224 -77.02650275192937
317 -12.083107578266883 -77.03038022714846
318 -12.085444433938743 -77.03653932852968
319 -12.007888338984447 -77.07259287226347
320 -11.994520092733904 -77.06676985707466
321 -11.972727827325928 -77.08536409196657
322 -11.99823602807316 -77.06285524214566
323 -11.945980691911204 -77.07220876154332
324 -11.98704561976698 -77.0761789283695
325 -11.997776429754984 -77.08109494221895
326 -11.986873115223766 -77.0693070369156
327 -11.999678417407234 -77.0770927769927
328 -11.950504096820985 -77.081742382405
329 -12.01108179393284 -77.07114654026515
330 -12.005095442500403 -77.07989277393189
331 -11.954866678719643 -77.07647314366473
332 -12.009679874200891 -77.0761175376476
333 -12.008554970996624 -77.0783908403021
334 -11.98407923138756 -77.06650007382353
335 -11.97534918054042 -77.06266451050452
336 -11.942585131758415 -77.07579534525885
337 -11.967988450497815 -77.06761715395366
338 -11.960873107964199 -77.07491559738871
339 -11.97693779607747 -77.0781167466375
340 -12.00115716048272 -77.0670474749214
341 -11.996676673733202 -77.06532203415544
342 -11.976587363523382 -77.07072731559644
343 -12.004300746752874 -77.07713528944926
344 -11.95130663773376 -77.08026085254949
345 -11.987991824107903 -77.078330259885
346 -11.964609467975007 -77.06553654025655
347 -12.004506200742703 -77.07196294049412
348 -12.069412738033169 -77.0668618713331
349 -12.078239913685431 -77.07239188945897
350 -12.079599396352831 -77.062621542331
351 -12.06991688945609 -77.06453708352913
352 -12.073577131724853 -77.06635753476462
353 -12.070969080998584 -77.06847359146583
354 -12.085563437508803 -77.0638035403263
355 -12.067994791709928 -77.07048132291429
356 -12.082527039911003 -77.07088619499824
357 -12.080477799088747 -77.06406519780833
358 -12.073636225309384 -77.05393321515683
359 -12.070620317160616 -77.06276892469526
360 -12.076573011294437 -77.07080506815365
361 -12.068945711932791 -77.07283305109816
362 -12.075504196149064 -77.06697707413782
363 -12.07431457710065 -77.05465173991429
364 -12.07338035509866 -77.06028212628036
365 -12.069115629247417 -77.05305935205003
366 -12.06938602139358 -77.06880882608989
367 -12.071492075073454 -77.07623476655206
368 -12.076299662329491 -77.0683500887025
369 -12.077764567909755 -77.07306743501373
370 -12.074079135178733 -77.06733698221913
371 -12.068963270826163 -77.06149358449805
372 -12.072334319286993 -77.07210839423988
373 -12.08349994160727 -77.06622308461604
374 -12.074131704773443 -77.06183103738361
375 -12.07059071600223 -77.05112145813048
376 -12.071881017229618 -77.05138103674565
377 -12.125406201474012 -77.01221271949419
378 -12.124143767482872 -77.00775356553352
379 -12.113029626584643 -77.04606958918689
380 -12.129884360827656 -77.03507056442284
381 -12.125910832137246 -77.03867540950273
382 -12.121471033908565 -77.01092293387123
383 -12.127129541568257 -77.01387581176877
384 -12.109080974451983 -77.02816710581654
385 -12.120255095764772 -77.03896233006964
386 -12.11707184079538 -77.00924840949693
387 -12.124467974351088 -77.03047500292797
388 -12.123974305274299 -77.0398590943417
389 -12.110827462287546 -77.05396720480485
390 -12.113455552446943 -77.04682295784751
391 -12.110524168697637 -77.0503675770976
392 -12.117362488540849 -77.01055143844603
393 -12.109617498476712 -77.04926831131824
394 -12.115045071875683 -77.04708267951436
395 -12.111184269509858 -77.0343021557455
396 -12.128751299129222 -77.01041050090966
397 -12.1250532791132 -77.00654145688706
398 -12.127493443419013 -77.02052723103527
399 -12.123013659272509 -77.03550020623277
400 -12.109655045993788 -77.0278676489091
401 -12.112656649603954 -77.04437622012529
402 -12.124226783024392 -77.01505679936275
403 -12.113379266052364 -77.03538420604582
404 -12.12368133624096 -77.0144749225925
405 -12.111836926136299 -77.04679854384487
406 -12.110078093126699 -76.99632575188615
407 -12.098306748682203 -76.98692345359484
408 -12.085710710410567 -76.98264208927145
409 -12.084564132948023 -76.99302243259883
410 -12.099486413197331 -76.99739200283656
411 -12.101865275812882 -76.98667389522166
412 -12.105515616463745 -76.98973106450171
413 -12.099764133589414 -76.98440822202403
414 -12.086299754694995 -76.98448847028965
415 -12.088480373636141 -76.9906602853281
416 -12.082754243091978 -76.98733411338794
417 -12.10542032925169 -76.98928124832334
418 -12.082234577343371 -76.98827062417031
419 -12.107853636539721 -77.00028513602685
420 -12.092522723012078 -76.99490048703404
421 -12.088800794171568 -77.00031106516366
422 -12.106644741349099 -76.98278953852225
423 -12.103642969023873 -77.00375740467408
424 -12.08792568428701 -76.99045437195262
425 -12.085938468941162 -76.9834817334218
426 -12.097668206813925 -76.98041024354902
427 -12.106361985472928 -77.00824670873722
428 -12.088027443764808 -76.99688339370162
429 -12.100743788225978 -76.98455006931441
430 -12.099923187208132 -76.99303141259648
431 -12.10265720908787 -76.99687119508172
432 -12.10332016399311 -76.99810949016359
433 -12.086798545803685 -76.99040907530332
434 -12.095137592017661 -76.98202504127156
435 -12.100801203276305 -77.03445038436475
436 -12.089322061121354 -77.03509424461032
437 -12.106847044319132 -77.01488428234781
438 -12.103978467004646 -77.05946819504256
439 -12.09953234874704 -77.04595147484369
440 -12.106683677989219 -77.05507362514
441 -12.108616382393569 -77.04190702676776
442 -12.093676874216724 -77.01222534511196
443 -12.10544704267786 -77.04432332493826
444 -12.105088283484566 -77.04286473243577
445 -12.092047645994121 -77.04973794266189
446 -12.09924815919586 -77.05617997153747
447 -12.104335676983409 -77.05950136971094
448 -12.091331800356484 -77.02194879941638
449 -12.091542702761712 -77.04396221499476
450 -12.104426056710643 -77.05496363238989
451 -12.104608016255739 -77.04934500235136
452 -12.098984756377302 -77.02269452018456
453 -12.094524645687933 -77.0397235326342
454 -12.108880274277203 -77.0519970219277
455 -12.089313306512329 -77.01099079280038
456 -12.095092119816426 -77.02993155987043
457 -12.106466603378786 -77.04214708143576
458 -12.093911132292622 -77.03992847705743
459 -12.098041365919832 -77.0125704539707
460 -12.103048575998887 -77.03448457480096
461 -12.104434021547961 -77.05199905065093
462 -12.093165761252829 -77.01974800352883
463 -12.10630448002061 -77.043430231012
464 -12.14248065683856 -76.98605458778628
465 -12.1150928545249 -76.97362739325482
466 -12.140493852085392 -77.00217227266602
467 -12.130659106244382 -77.00454260436494
468 -12.110260452901006 -76.95408148024704
469 -12.151978216403984 -76.985760962814
470 -12.157593857051172 -77.0072335148837

In [109]:
gdf_puntos_con_direcciones = gdf_puntos.copy()
gdf_puntos_con_direcciones["address"] = address_list
gdf_puntos_con_direcciones

,distrito,departamento,geometry,address
0,LIMA,LIMA,POINT (-77.00947 -12.05707),"Jirón Junín, San Cayetano, El Agustino, Lima, ..."
1,LIMA,LIMA,POINT (-77.08194 -12.03984),"3300, Avenida Enrique Meiggs, Urbanización Ind..."
2,LIMA,LIMA,POINT (-77.0545 -12.04442),"Avenida República de Argentina, Mirones, Lima,..."
3,LIMA,LIMA,POINT (-77.06685 -12.0466),"Luis Carranza, Mirones, Lima, Lima Metropolita..."
4,LIMA,LIMA,POINT (-77.03953 -12.06268),"Urbanización Cercado de Lima, Lima, Lima Metro..."
...,...,...,...,...
488,SANTIAGO DE SURCO,LIMA,POINT (-77.00642 -12.1413),"Urbanización Cooviecma, Santiago de Surco, Lim..."
489,SANTIAGO DE SURCO,LIMA,POINT (-76.99853 -12.14501),"Avenida Paseo de la República, Urbanización Sa..."
490,SANTIAGO DE SURCO,LIMA,POINT (-77.00842 -12.1445),"Calle Teniente José Melitón Rodríguez, Urbaniz..."
491,SANTIAGO DE SURCO,LIMA,POINT (-76.98765 -12.1632),"Pasaje Augusto López Rodríguez, Viñedos de Sur..."
492,SANTIAGO DE SURCO,LIMA,POINT (-76.97453 -12.1259),"Will Market Valle Hermoso, 176, Los Laureles, ..."

## Guardando output

In [110]:
gdf_puntos_con_direcciones.to_file("propiedades.geojson", driver="GeoJSON")

In [ ]:
# probamos la carga de data.
load_test = gpd.read_file("propiedades.geojson")
load_test

,distrito,departamento,address,geometry
0,LIMA,LIMA,"Jirón Junín, San Cayetano, El Agustino, Lima, ...",POINT (-77.00947 -12.05707)
1,LIMA,LIMA,"3300, Avenida Enrique Meiggs, Urbanización Ind...",POINT (-77.08194 -12.03984)
2,LIMA,LIMA,"Avenida República de Argentina, Mirones, Lima,...",POINT (-77.0545 -12.04442)
3,LIMA,LIMA,"Luis Carranza, Mirones, Lima, Lima Metropolita...",POINT (-77.06685 -12.0466)
4,LIMA,LIMA,"Urbanización Cercado de Lima, Lima, Lima Metro...",POINT (-77.03953 -12.06268)
...,...,...,...,...
488,SANTIAGO DE SURCO,LIMA,"Urbanización Cooviecma, Santiago de Surco, Lim...",POINT (-77.00642 -12.1413)
489,SANTIAGO DE SURCO,LIMA,"Avenida Paseo de la República, Urbanización Sa...",POINT (-76.99853 -12.14501)
490,SANTIAGO DE SURCO,LIMA,"Calle Teniente José Melitón Rodríguez, Urbaniz...",POINT (-77.00842 -12.1445)
491,SANTIAGO DE SURCO,LIMA,"Pasaje Augusto López Rodríguez, Viñedos de Sur...",POINT (-76.98765 -12.1632)
492,SANTIAGO DE SURCO,LIMA,"Will Market Valle Hermoso, 176, Los Laureles, ...",POINT (-76.97453 -12.1259)

# Generacion de usuarios aleatorios

In [ ]:
# Table users {
#   id UUID [pk]
#   name VARCHAR
#   email VARCHAR
#   phone VARCHAR
#   role TEXT
#   password_hash TEXT
#   google_id TEXT //NULL si no tiene ID
#   created_at TIMESTAMP
#   updated_at TIMESTAMP

#   // role: client, agent, admin,
#   // Relaciones
#   // 1:N con leads si aplica en el futuro
# }

In [135]:
from faker import Faker
import secrets
from datetime import datetime

In [114]:
fake = Faker()

In [139]:
def generate_fake_user():
    "generates a faker user"
    data = {
        "name": fake.name(),
        "email": fake.email(),
        "phone": fake.phone_number(),
        "role": "agent",  # client, agent,admin
        "password_hash": secrets.token_hex(16),
        "google_id": None,
        "created_at": datetime.now().isoformat(),
        "updated_at": datetime.now().isoformat(),
    }
    return data

In [ ]:
user_data = pd.DataFrame(
    data=[],
    columns=[
        "name",
        "email",
        "phone",
        "role",
        "password_hash",
        "google_id",
        "created_at",
        "updated_at",
    ],
)

for i in range(1000):
    user_data.loc[i] = generate_fake_user()

user_data

,name,email,phone,role,password_hash,google_id,created_at,updated_at
0,Justin Cardenas,elizabethscott@example.net,870-216-4072,agent,1494958f642bb521f5debfba73f5f4ef,None,2025-06-17T16:20:17.189701,2025-06-17T16:20:17.189701
1,Craig Coleman,ellissummer@example.net,001-626-731-3556x015,agent,d7fef1484628e4603253952469c902fb,None,2025-06-17T16:20:17.189701,2025-06-17T16:20:17.189701
2,Cassandra Wright,ashley97@example.com,(351)366-9035x039,agent,9884171ecb4a502e111ba01b4467274e,None,2025-06-17T16:20:17.191745,2025-06-17T16:20:17.191745
3,Renee Miller,xavier01@example.net,6575078532,agent,744e0a6deef869bdeeef38b866afee5e,None,2025-06-17T16:20:17.192933,2025-06-17T16:20:17.192933
4,Elizabeth Brooks,mary87@example.net,+1-630-760-1704,agent,a546aeb76c26feca0d0b99066395e6d7,None,2025-06-17T16:20:17.193930,2025-06-17T16:20:17.193930
...,...,...,...,...,...,...,...,...
995,Monica Johnson,jeremy62@example.org,531-802-3784x442,agent,5655bfaf98553c5470d57aba9c2cd21b,None,2025-06-17T16:20:18.066229,2025-06-17T16:20:18.066229
996,Barbara Livingston,vdeleon@example.org,859-372-5851x72371,agent,3a23e354b31cabbdcb2d063bea1e7614,None,2025-06-17T16:20:18.067232,2025-06-17T16:20:18.067232
997,Janet Wade,christinahogan@example.com,(933)610-4869x7916,agent,d2873b9cf873884bf31be1de5f5160a8,None,2025-06-17T16:20:18.068229,2025-06-17T16:20:18.068229
998,Bonnie Casey,lhess@example.com,723-534-7100x00189,agent,8d59e42c4e119d3fb839f81ddb9c2159,None,2025-06-17T16:20:18.069229,2025-06-17T16:20:18.069229
999,Michelle Gilbert,austinmorris@example.org,9154997532,agent,7ac64929dc55f4096a255b4026c8614d,None,2025-06-17T16:20:18.070232,2025-06-17T16:20:18.070232

In [ ]:
# saving to file
user_data.to_csv("data/generated_data/users")

# Generacion de datos para la tabla Properties

In [153]:
# Table properties {
#   id UUID [pk]
#   title VARCHAR
#   description TEXT
#   property_type TEXT
#   operation_type TEXT
#   location TEXT
#   address TEXT
#   price NUMERIC
#   status VARCHAR
#   user_id UUID [ref: > users.id]
#   created_at TIMESTAMP
#   updated_at TIMESTAMP
#   geolocation GEOGRAPHY(Point, 4326)
#   // Relaciones
#   // N:1 con users
#   // 1:N con images
#   // 1:N con leads
# }

Vamos a usar un modelo open source: mistral-7b-instruct para generar descripciones y titulos atractivos de las propiedades.

In [182]:
import json
import ollama

In [198]:
random.choice(["casa", "propiedad"])

'casa'

In [200]:
properties = gdf_puntos_con_direcciones.copy()
properties["property_type"] = [
    random.choice(["casa", "departamento", "cuarto", "mini-departamento", "local"])
    for i in range(len(properties))
]
properties["operation_type"] = [
    random.choice(["venta", "alquiler"]) for i in range(len(properties))
]
properties

,distrito,departamento,geometry,address,property_type,operation_type
0,LIMA,LIMA,POINT (-77.00947 -12.05707),"Jirón Junín, San Cayetano, El Agustino, Lima, ...",casa,venta
1,LIMA,LIMA,POINT (-77.08194 -12.03984),"3300, Avenida Enrique Meiggs, Urbanización Ind...",departamento,venta
2,LIMA,LIMA,POINT (-77.0545 -12.04442),"Avenida República de Argentina, Mirones, Lima,...",local,alquiler
3,LIMA,LIMA,POINT (-77.06685 -12.0466),"Luis Carranza, Mirones, Lima, Lima Metropolita...",departamento,venta
4,LIMA,LIMA,POINT (-77.03953 -12.06268),"Urbanización Cercado de Lima, Lima, Lima Metro...",local,venta
...,...,...,...,...,...,...
488,SANTIAGO DE SURCO,LIMA,POINT (-77.00642 -12.1413),"Urbanización Cooviecma, Santiago de Surco, Lim...",casa,alquiler
489,SANTIAGO DE SURCO,LIMA,POINT (-76.99853 -12.14501),"Avenida Paseo de la República, Urbanización Sa...",mini-departamento,alquiler
490,SANTIAGO DE SURCO,LIMA,POINT (-77.00842 -12.1445),"Calle Teniente José Melitón Rodríguez, Urbaniz...",casa,alquiler
491,SANTIAGO DE SURCO,LIMA,POINT (-76.98765 -12.1632),"Pasaje Augusto López Rodríguez, Viñedos de Sur...",mini-departamento,alquiler
492,SANTIAGO DE SURCO,LIMA,POINT (-76.97453 -12.1259),"Will Market Valle Hermoso, 176, Los Laureles, ...",departamento,alquiler

In [ ]:
responses = []

for _, location in properties.iterrows():
    address = location.address
    property_type = location.property_type
    operation_type = location.operation_type

    prompt = (
        f"Genera un título y descripción para un(a) {property_type} en {operation_type} en la dirección: {address}.\
            La respuesta debe brindarse en ESPAÑOL y en formato JSON.\
            El título debe tener una extensión máxima de 15 palabras.\
            La descripción debe tener una extensión máxima de 50 palabras.\
            Por ejemplo:"
        ""
        + "{'Título': 'Casa cómoda y tradicional en el corazón de Cusco', \
            'Descripción': 'Bienvenidos a esta hermosa y cómoda casa situada en el corazón de la ciudad histórica de Cusco'}"
    )

    raw_response = ollama.chat(
        model="mistral", messages=[{"role": "user", "content": prompt}]
    )

    # tratamos de parsear la respuesta , o dejamos en blanco.
    try:
        format_reponse = json.loads(raw_response["message"]["content"])
        print(_, "succeed")
    except Exception as e:
        print(e)
        format_response = {"Título": None, "Descripción": None}
        print(_, "error")

    responses.append(format_reponse)

0 succeed
1 succeed
2 succeed
3 succeed
4 succeed
5 succeed
6 succeed
7 succeed
8 succeed
9 succeed
10 error
11 succeed
12 succeed
13 succeed
14 succeed
15 succeed
16 succeed
17 succeed
18 succeed
19 succeed
20 succeed
21 succeed
22 succeed
23 succeed
24 succeed
25 succeed
26 succeed
27 succeed
28 succeed
29 succeed
30 succeed
31 succeed
32 succeed
33 succeed
34 succeed
35 succeed
36 succeed
37 succeed
38 succeed
39 succeed
40 succeed
41 succeed
42 succeed
43 succeed
44 succeed
45 error
46 succeed
47 succeed
48 succeed
49 succeed
50 succeed
51 succeed
52 succeed
53 succeed
54 succeed
55 succeed
56 succeed
57 succeed
58 succeed
59 succeed
60 succeed
61 succeed
62 succeed
63 succeed
64 succeed
65 succeed
66 error
67 succeed
68 succeed
69 succeed
70 error
71 succeed
72 error
73 succeed
74 succeed
75 succeed
76 succeed
77 succeed
78 succeed
79 succeed
80 error
81 succeed
82 succeed
83 succeed
84 succeed
85 succeed
86 succeed
87 succeed
88 succeed
89 succeed
90 succeed
91 error
92 succeed
93 succeed
94 succeed
95 succeed
96 succeed
97 succeed
98 succeed
99 succeed
100 succeed
101 succeed
102 succeed
103 succeed
104 error
105 succeed
106 succeed
107 succeed
108 succeed
109 succeed
110 succeed
111 error
112 succeed
113 succeed
114 succeed
115 succeed
116 succeed
117 succeed
118 succeed
119 succeed
120 succeed
121 succeed
122 succeed
123 succeed
124 succeed
125 succeed
126 succeed
127 succeed
128 succeed
129 succeed
130 succeed
131 succeed
132 succeed
133 succeed
134 succeed
135 error
136 succeed
137 succeed
138 succeed
139 succeed
140 succeed
141 succeed
142 succeed
143 succeed
144 succeed
145 error
146 succeed
147 succeed
148 succeed
149 succeed
150 succeed
151 succeed
152 succeed
153 succeed
154 succeed
155 succeed
156 succeed
157 succeed
158 succeed
159 succeed
160 succeed
161 succeed
162 succeed
163 succeed
164 succeed
165 succeed
166 succeed
167 succeed
168 succeed
169 succeed
170 error
171 succeed
172 succeed
173 succeed
174 succeed
175 succeed
176 succeed
177 succeed
178 succeed
179 error
180 succeed
181 succeed
182 succeed
183 succeed
184 succeed
185 succeed
186 succeed
187 succeed
188 succeed
189 succeed
190 succeed
191 succeed
192 succeed
193 succeed
194 succeed
195 succeed
196 succeed
197 succeed
198 succeed
199 error
200 succeed
201 succeed
202 succeed
203 succeed
204 succeed
205 succeed
206 succeed
207 succeed
208 succeed
209 succeed
210 succeed
211 succeed
212 error
213 succeed
214 succeed
215 succeed
216 succeed
217 succeed
218 succeed
219 succeed
220 succeed
221 succeed
222 succeed
223 succeed
224 succeed
225 succeed
226 succeed
227 succeed
228 succeed
229 succeed
230 succeed
231 succeed
232 succeed
233 succeed
234 error
235 succeed
236 succeed
237 succeed
238 succeed
239 succeed
240 succeed
241 succeed
242 succeed
243 succeed
244 succeed
245 error
246 succeed
247 error
248 succeed
249 succeed
250 succeed
251 succeed
252 succeed
253 succeed
254 succeed
255 succeed
256 error
257 error
258 succeed
259 succeed
260 succeed
261 succeed
262 succeed
263 succeed
264 succeed
265 succeed
266 succeed
267 succeed
268 succeed
269 succeed
270 succeed
271 succeed
272 succeed
273 succeed
274 succeed
275 succeed
276 succeed
277 succeed
278 succeed
279 succeed
280 succeed
281 succeed
282 succeed
283 succeed
284 succeed
285 succeed
286 succeed
287 succeed
288 succeed
289 succeed
290 succeed
291 error
292 succeed
293 succeed
294 succeed
295 error
296 succeed
297 succeed
298 succeed
299 succeed
300 succeed
301 succeed
302 succeed
303 succeed
304 succeed
305 succeed
306 succeed
307 succeed
308 succeed
309 succeed
310 error
311 succeed
312 succeed
313 succeed
314 succeed
315 succeed
316 error
317 succeed
318 succeed
319 succeed
320 error
321 succeed
322 succeed
323 succeed
324 succeed
325 succeed
326 succeed
327 succeed
328 succeed
329 succeed
330 succeed
331 succeed
332 succeed
333 succeed
334 succeed
335 succeed
336 succeed
337 succeed
338 succeed
339 succeed
340 succeed
341 succeed
342 succeed
343 succeed
344 succeed
345 succeed
346 succeed
347 succeed
348 succeed
349 succeed
350 succeed
351 succeed
352 succeed
353 succeed
354 succeed
355 error
356 succeed
357 succeed
358 succeed
359 succeed
360 succeed
361 succeed
362 succeed
363 succeed
364 succeed
365 error
366 succeed
367 succeed
368 succeed
369 succeed
370 succeed
371 succeed
372 succeed
373 succeed
374 succeed
375 succeed
376 succeed
377 error
378 succeed
379 succeed
380 succeed
381 succeed
382 succeed
383 succeed
384 error
385 succeed
386 succeed
387 succeed
388 error
389 succeed
390 succeed
391 succeed
392 succeed
393 succeed
394 succeed
395 succeed
396 succeed
397 succeed
398 succeed
399 succeed
400 succeed
401 succeed
402 succeed
403 succeed
404 succeed
405 succeed
406 succeed
407 succeed
408 succeed
409 succeed
410 succeed
411 succeed
412 succeed
413 succeed
414 succeed
415 succeed
416 succeed
417 succeed
418 succeed
419 succeed
420 succeed
421 succeed
422 succeed
423 error
424 succeed
425 succeed
426 error
427 succeed
428 succeed
429 succeed
430 succeed
431 succeed
432 succeed
433 succeed
434 succeed
435 succeed
436 succeed
437 succeed
438 succeed
439 succeed
440 succeed
441 succeed
442 succeed
443 succeed
444 succeed
445 succeed
446 succeed
447 succeed
448 succeed
449 succeed
450 succeed
451 succeed
452 succeed
453 succeed
454 succeed
455 succeed
456 succeed
457 succeed
458 succeed
459 succeed
460 succeed
461 error
462 succeed
463 succeed
464 succeed
465 succeed
466 succeed
467 succeed
468 succeed
469 succeed
470 succeed
471 succeed
472 succeed
473 succeed
474 succeed
475 succeed
476 succeed
477 succeed
478 succeed
479 succeed
480 succeed
481 succeed
482 succeed
483 succeed
484 succeed
485 succeed
486 succeed
487 succeed
488 succeed
489 succeed
490 succeed
491 succeed
492 succeed

In [ ]:
# output check:
responses

[{'Título': 'Casa moderna en Jirón Junín, San Cayetano',
  'Descripción': 'Venta de una hermosa y amplia casa ubicada en el corazón de El Agustino, Lima. Área verde y accesibilidad a servicios públicos. No pierdas la oportunidad!'},
 {'Título': 'Departamento moderno en Urbanización Industrial Wiese, Lima',
  'Descripción': 'Ofrecemos un departamento bien ubicado en la urbanización Industrial Wiese, Lima Metropolitana. Equipado con comodidades y a solo minutos del centro de la ciudad.'},
 {'Título': 'Apartamento moderno en Mirones, Lima',
  'Descripción': 'Espacioso apartamento con vista a Avenida República de Argentina, ofrece cómoda estancia y baño. Zona tranquila de Lima Metropolitana.'},
 {'Título': 'Departamento lujoso en Mirones, Lima',
  'Descripción': 'Departamento elegante con vistas panorámicas de la ciudad de Lima, ubicado en el exclusivo distrito de Mirones.'},
 {'Título': 'Casa moderna en exclusiva Urbanización Cercado de Lima',
  'Descripción': 'Experimenta vivir en un espacio moderno y cómodo situado en el corazón de la ciudad de Lima, con acceso a servicios públicos, comercios y transporte.'},
 {'Título': 'Casa en Parqueadero, Lima Centro',
  'Descripción': 'Apartamento moderno en Urbanización Cercado de Lima. Muy cómodo y cerca de servicios públicos.'},
 {'Título': 'Mini-departamento moderno en Barrio Monserrate, Lima',
  'Descripción': 'Ubicado en el barrio emblemático de Monserrate, este mini-departamento ofrece comodidad y estilo con vista a la ciudad. Área comunal disponible.'},
 {'Título': 'Departamento lujoso en Urbanización Cercado de Lima',
  'Descripción': 'Átentate a este departamento exclusivo en Avenida Alfonso Ugarte, Lima. Espacioso, moderno y bien ubicado en Urbanización Cercado de Lima.'},
 {'Título': 'Moderno mini-departamento en Barrios Altos',
  'Descripción': 'Encuentra este apartamento moderno y cómodo ubicado en Barrios Altos, Urbanización Las Nieves, Lima. Amenidades incluyen jardines, seguridad 24/7 y acceso fácil a todos los servicios.'},
 {'Título': 'Mini-departamento moderno en Urbanización Cercado de Lima',
  'Descripción': 'Ubicado en la emblemática Urbanización Cercado de Lima, este mini-departamento ofrece una estancia cómoda con baño, cocina integral y balcón. Ideal para disfrutar de la vida urbana de Lima.'},
 {'Título': 'Mini-departamento moderno en Urbanización Cercado de Lima',
  'Descripción': 'Ubicado en la emblemática Urbanización Cercado de Lima, este mini-departamento ofrece una estancia cómoda con baño, cocina integral y balcón. Ideal para disfrutar de la vida urbana de Lima.'},
 {'Título': 'Casa alquiler: Urb. Cercado de Lima, Jirón Cailloma',
  'Descripción': 'Ático cómodo con balcón en Urbanización Cercado de Lima, ofrece 2 habitaciones, baño completo y cocina completa.'},
 {'Título': 'Local comercial centricamente ubicado en Centro Comercial Cachina Fashion',
  'Descripción': 'Encuentra un local comercial idealmente ubicado en el centro comercial Cachina Fashion, ofreciendo una gran visibilidad y afluencia de clientes en la intersección de Jirón Rodolfo Beltran en Lima.'},
 {'Título': 'Estudio moderno en Urbanización Industrial Wiese, Lima',
  'Descripción': 'Este apartamento estudio ubicado en la Urbano Express ofrece un espacio cómodo y funcional, ideálido para quien busca vivir cerca de las principales industrias de la ciudad.'},
 {'Título': 'Casa moderna en exclusivo Los Fresnos',
  'Descripción': 'Alquiler de una casa acogedora y bien ubicada en etapa uno de Los Fresnos, Las Brisas, Lima. Amenidades como jardín interior, baños completos e instalaciones recientemente renovadas.'},
 {'Título': 'Mini-departamento confortable en Barrios Altos, Lima',
  'Descripción': 'Átenta visita a este mini-departamento moderno y acogedor situado en la tranquila Urbanización Barrios Altos, en Lima. ¡Te esperamos!'},
 {'Título': 'Mini-departamento elegante en Eternit, Lima',
  'Descripción': 'Encuentra tu hogar ideal en este mini-departamento confortablemente situado en la tranquila y moderna comunidad de Eternit, Lima. Convenientemente ubicado en 1 de Octubre.'},
 {'Título': 'Departamento moderno en Conde de la Vega Alta, Lima',
  'Descripción': 'Aprovecha este gran espacio y ubicación estratégica en el corazón de Lima Metropolitana. Departamento con acceso a servicios públicos y comodidades.'},
 {'Título': 'Apartamento moderno en Nuevo Mercado Caquetá',
  'Descripción': 'Bienvenido a este apartamento acogedor y funcional, situado en el corazón de Conde de la Vega Alta, Lima.'},
 {'Título': 'Moderno apartamento en Centro Cultural Sama',
  'Descripción': 'Ofrecemos un espacioso apartamento moderno ubicado en el Centro Cultural Sama, una zona llena de actividades culturales y comunitarias. El inmueble posee habitaciones amplias, baños limpios y tecnología actualizada. ¡Aquí tienes espacio para vivir cómodamente!'},
 {'Título': 'Apartamento moderno en Ángeles, Lima',
  'Descripción': 'Ático cómodo y bien ubicado en Ángeles, 1 de Octubre, zona central de Lima Metropolitana. Disfruta de un ambiente agradable y las comodidades más modernas.'},
 {'Título': 'Gran Hotel Bolivar: Lima Centro - Sucumbió en el Jirón de la Unión',
  'Descripción': 'Inmueble con gran historia y presencia, el Gran Hotel Bolivar se encuentra en el corazón del centro histórico de Lima. Con una combinación única de elegancia y tradición peruana, este hotel ofrece un hospedaje único para los viajeros.'},
 {'Título': 'Departamento confortable en Unidad Vecinal de Mirones, Lima',
  'Descripción': 'Ático acogedor y moderno ubicado en el corazón del distrito residencial de Mirones, ofrece una vista impresionante de la ciudad. Contiene 2 dormitorios, una cocina integral, una sala de estar, wc, y un terrazzo con vistas. Ideal para quien busca vivir en armonía con su entorno.'},
 {'Título': 'Mini-departamento moderno en Avenida Naciones Unidas, Chacra Ríos Norte',
  'Descripción': 'Átento mini-departamento ubicado en la Avenida Naciones Unidas de Lima, con estacionamiento y acceso rápido a todo el área metropolitana. Inmueble renovado y funcional.'},
 {'Título': 'Departamento moderno en Avenida Alejandro Tirado, Santa Beatriz',
  'Descripción': 'Ofrecemos un espacioso departamento con vistas panorámicas en la prestigiosa avenida Alejandro Tirado de Santa Beatriz, Lima. Área de servicio y estacionamiento incluido.'},
 {'Título': 'Casa moderna en Mirones, Lima Metropolitana',
  'Descripción': 'Ubicación privilegiada en Avenida Guillermo Dansey, ofrece esta casa luminosa y cómoda. Algunas de las características incluyen espacios abiertos, instalaciones recientes y acceso fácil a la ciudad.'},
 {'Título': 'Mini-departamento moderno en Barrio Monserrate, Lima',
  'Descripción': 'Este mini-departamento ubicado en Jirón Tayacaja ofrece espacio y lujos con un estilo contemporáneo. Se encuentra en el popular Barrio Monserrate de Lima.'},
 {'Título': 'Casa moderna en Vía Expresa Línea Amarilla, Lima',
  'Descripción': 'Espaciosos apartamentos disponibles para alquiler en un edificio moderno de oficinas en la Vía Expresa Línea Amarilla, en el corazón de Lima.'},
 {'Título': 'Departamento moderno en Plaza Vea, Lima',
  'Descripción': 'Ofrecemos un departamento estilo Lima moderno, ubicado en Plaza Vea, Avenida Alfonso Ugarte, en la urbanización Cercado de Lima. Ideal para vivir y disfrutar del mejor que ofrece la capital peruana.'},
 {'Título': 'Cuarto moderno en Ancón, Lima',
  'Descripción': 'Ático con vista panorámica en el exclusivo distrito de Ancón. Comunicaciones rápidas y servicios luxuriantes en este espacio único.'},
 {'Título': 'Mini-Departamento moderno en Ancón, Lima',
  'Descripción': 'Ofrecemos un mini-departamento moderno y cómodo en el distrito elegido de Ancón, Lima. Acerca de ti para vivir e disfrutar de la costa peruana.'},
 {'Título': 'Casa luminosa en Ancón, Lima',
  'Descripción': 'Atractiva y luminosa vivienda en el popular sector de Ancón, ofreciendo acceso a playas y servicios públicos. Ideal para una familia o individuo en busca de un hogar cómodo.'},
 {'Título': 'Casa moderna en costas de Ancón',
  'Descripción': 'Alegre y acogedora casa en la playa de Ancón, ofreciendo hermosos vistas al mar. Muebles nuevos y servicios completos.'},
 {'Título': 'Vivienda lujosa en Ancón, Lima',
  'Descripción': 'Explora esta hermoso apartamento de lujo, ubicado en el exclusivo distrito de Ancón, en la ciudad de Lima. Ofrece una vista panorámica maravillosa y una amplia terraza para disfrutar del clima tropical.'},
 {'Título': 'Cuarto moderno y cómodo en Ancón, Lima',
  'Descripción': 'Elegí este cuarto confortable e iluminado ubicado en el corazón de la ciudad de Ancón, Lima. Disfruta del mar a un paso y de las excelentes comunicaciones con el resto de la ciudad.'},
 {'Título': 'Casa lujosa en el encanto de Ancón',
  'Descripción': 'Disfruta del charme de Ancón en esta moderna y cómoda casa de alquiler. Con acceso a playas, restaurantes y parques, encuentra todo lo necesario para una estadía increíble en esta ciudad maravillosa.'},
 {'Título': 'Lujoso Apartamento en Playa de Ancón, Lima',
  'Descripción': 'Este moderno apartamento se encuentra en una posición privilegiada frente a la playa de Ancón. Ofrece 2 habitaciones, 2 baños y una cocina equipada.'},
 {'Título': 'Mini-departamento lujoso en el exclusivo Ancón',
  'Descripción': 'Este moderno mini-departamento ofrece una vida cómoda y privilegiada, ubicado en la prestigiosa zona de Ancón, Lima.'},
 {'Título': 'Apartamento moderno en costa Ancón, Lima',
  'Descripción': 'Experimenta la vida al mar! Apartamento moderno y acogedor en la hermosa playa de Ancón, Lima.'},
 {'Título': 'Casa elegante en tranquilo Ancón',
  'Descripción': 'Diseñada para agradecer a su dueño, ofrece 3 dormitorios, amplia cocina y jardín privado. Ideal para quien busca relajación en Lima.'},
 {'Título': 'Departamento moderno en exclusiva zona de Ancón, Lima',
  'Descripción': 'Experimente la vida en la bella zona residencial de Ancón, Lima. Únete a este departamento moderno bien situado y disfrute de una gran comodidad.'},
 {'Título': 'Casa moderna en el lujoso sector de Ancón, Lima',
  'Descripción': 'Atractiva vivienda de lujo ubicada en el exclusivo sector de Ancón, Lima. Con vistas panorámicas y servicios excepcionales.'},
 {'Título': 'Apartamento lujoso en la costa de Ancón',
  'Descripción': 'Experimente la vida en la playa con este apartamento moderno y confortable ubicado en el corazón de Ancón, Lima.'},
 {'Título': 'Mini-departamento moderno en el lujoso distrito de Ancón',
  'Descripción': 'Encuentra tu nuevo hogar en este espacioso mini-departamento ubicado en la exclusiva zona de Ancón, Lima. El apartamento ofrece una vista espectacular al mar y cuenta con una decoración moderna y confortable.'},
 {'Título': 'Mini-departamento exclusivo en Ancón, Lima',
  'Descripción': 'Este moderno y bien ubicado mini-departamento ofrece una experiencia inmejorable. Con vistas al mar, está equipado con todos los amenidades necesarias para un estilo de vida cómodo y agradable.'},
 {'Título': 'Mini-departamento exclusivo en Ancón, Lima',
  'Descripción': 'Este moderno y bien ubicado mini-departamento ofrece una experiencia inmejorable. Con vistas al mar, está equipado con todos los amenidades necesarias para un estilo de vida cómodo y agradable.'},
 {'Título': 'Atractivo mini-departamento en Ancón, Lima',
  'Descripción': 'Ofrecemos un mini-departamento moderno y acogedor ubicado en el distrito de Ancón, cerca de la costa. Aprovecha este espacio funcional y confortable.'},
 {'Título': 'Departamento moderno en el exclusivo distrito de Ancón',
  'Descripción': 'Ubicado en el distrito elegido del Lima Metropolitano, este departamento ofrece una combinación perfecta entre tranquilidad y acceso a todos los servicios. Está lleno de lujo y tecnología moderna.'},
 {'Título': 'Departamento moderno en Ancón, Lima',
  'Descripción': 'Ático elegante en un edificio exclusivo, ofreciendo vistas panorámicas de la costa y el mar. Amenidades incluyen balcón privado, aire acondicionado y garaje.'},
 {'Título': 'Mini-departamento moderno en Ancón, Lima',
  'Descripción': 'Ático elegante en Señor de La Ascención, ofreciendo vistas panorámicas y ubicado cerca del mar.'},
 {'Título': 'Atractivo Apartamento con vistas al Océano en Ancon, Lima',
  'Descripción': 'Ofrecemos un apartamento moderno y acogedor, rodeado de bellas vistas del océano Pacífico. Convenientemente situado en la playa de Ancon, ideal para disfrutar el clima tropical de Lima.'},
 {'Título': 'Departamento lujoso en prestigioso Ancón',
  'Descripción': 'Enjoy this spacious and modern apartment located in the exclusive district of Ancón, Lima. Featuring stunning sea views, high-end finishes and a prime location.'},
 {'Título': 'Casa moderna en costa litoral de Lima',
  'Descripción': 'Atractiva propiedad ubicada en la desbordante playa de Ancón, ofreciendo una vista impresionante y un estilo contemporáneo.'},
 {'Título': 'Departamento lujoso en costa del Ancón, Lima',
  'Descripción': 'Área moderna y acogedora con vistas impresionantes al mar. Amenidades incluyen balcón, aire acondicionado y wifi.'},
 {'Título': 'Casa luminosa en Ancón, playa cercana',
  'Descripción': 'Alquila una espaciosa e iluminada casa ubicada en Ancón, Lima Metropolitana. A solo pasos de la playa y con vistas al mar.'},
 {'Título': 'Apartamento moderno en el lujoso distrito de Ancón',
  'Descripción': 'Experimenta la vida de lujo en este apartamento elegante y acogedor situado en el distrito exclusivo de Ancón, Lima. El apartamento cuenta con una cocina integral, dormitorio principal y un jacuzzi privado para que disfrutes de una estadía inolvidable.'},
 {'Título': 'Casa lujosa en playa en Ancón, Lima',
  'Descripción': 'Ventála ahora! Magnífica residencia en un entorno privilegiado de Ancón, Lima. Posee 4 habitaciones y ofrece una vista increíble al mar.'},
 {'Título': 'Departamento moderno en Ancón, Lima',
  'Descripción': 'Alquilas un departamento lujoso e innovador ubicado en Ancón, Lima. Con acceso a playa y comodidades en el corazón de la ciudad.'},
 {'Título': 'Mini-departamento moderno en Ate, Lima',
  'Descripción': 'Este moderno mini-departamento se encuentra en la zona tranquila y práctica de Ate, ofreciendo comodidad y facilidades.'},
 {'Título': 'Mini-departamento cómodo en centro de Ate',
  'Descripción': 'Ático moderno y bien ubicado en el distrito de Ate, Lima. Contiene un espacio abierto combinando cocina, sala y habitación principal, con balcón a la vista. Completa con servicios públicos, aire acondicionado e internet. Estacionamiento disponible.'},
 {'Título': 'Mini-departamento cómodo en Ate, Lima',
  'Descripción': 'Espacioso mini-departamento disponible para alquiler en Ate, Lima. Área comunal y dormitorio privado, cerca de servicios públicos y transporte.'},
 {'Título': 'Mini-departamento elegante en Prolongación Javier Prado Este',
  'Descripción': 'Encuentra este apartamento moderno y lleno de lujo en Santa Ana, Ate, Lima. Contiene espacios comunes e incluso un balcón con vistas impresionantes.'},
 {'Título': 'Departamento moderno en Vitarte, Ate',
  'Descripción': 'Experimentá este departamento moderno ubicado en la zona residencial de Vitarte, Ate, Lima. Con vistas agradables y acceso rápido a varias áreas comerciales.'},
 {'Título': 'Mini-departamento confortable en Naciones Unidas, Ate',
  'Descripción': 'Está buscando un mini-dep. en Lima? ¡Este lo ofrece! Situado cerca de las Naciones Unidas, cuenta con espacios cómodos y servicios modernos.'},
 {'Título': 'Casa moderna en el centro de Ate, Lima',
  'Descripción': 'Atractiva propiedad en la zona central de Ate, ofreciendo comodidad y acceso fácil a los principales puntos de interés de la ciudad.'},
 {'Título': 'Departamento moderno en el centro de Ate, Lima',
  'Descripción': 'Este departamento es una gran oportunidad para vivir en el centro de Ate. Ofrece comodidad y estilo, ideal para cualquier tipo de vida.'},
 {'Título': 'Departamento moderno en el centro de Ate, Lima',
  'Descripción': 'Este departamento es una gran oportunidad para vivir en el centro de Ate. Ofrece comodidad y estilo, ideal para cualquier tipo de vida.'},
 {'Título': 'Departamento moderno en Vitarte, Ate, Lima',
  'Descripción': 'Atractivo departamento con estilo contemporáneo ubicado en el distrito de Vitarte, Ate, en la ciudad metropolitana de Lima. Convenientemente situado y equipado con todos los servicios.'},
 {'Título': 'Casa lujosa en Club Villa Tusán, Chaclacayo, Lima',
  'Descripción': 'Una opción excepcional para vivir en un entorno exclusivo y tranquilo. Esta casa de lujo se encuentra en el corazón de Club Villa Tusán, en la carretera Central de Chaclacayo, Ate, Lima Metropolitana.'},
 {'Título': 'Mini-departamento moderno en Ate, Lima',
  'Descripción': 'Encuentra este atractivo mini-departamento ubicado en el distrito de Ate, ofreciendo un espacio funcional y cómodo con acceso fácil a infraestructuras.'},
 {'Título': 'Mini-departamento moderno en Ate, Lima',
  'Descripción': 'Encuentra este atractivo mini-departamento ubicado en el distrito de Ate, ofreciendo un espacio funcional y cómodo con acceso fácil a infraestructuras.'},
 {'Título': 'Apartamento moderno en Antiguo Mercado Ceres, Vitarte',
  'Descripción': 'Encuentra un espacio acogedor y lleno de tecnología en este apartamento en el popular distrito de Ate, a solo pasos del antiguo mercado Ceres. No dudes en visitarlo!'},
 {'Título': 'Apartamento moderno en Antiguo Mercado Ceres, Vitarte',
  'Descripción': 'Encuentra un espacio acogedor y lleno de tecnología en este apartamento en el popular distrito de Ate, a solo pasos del antiguo mercado Ceres. No dudes en visitarlo!'},
 {'Título': 'Atractivo apartamento en el corazón de Ate, Lima',
  'Descripción': 'Ofrecemos un apartamento ameno ubicado en el corazón de la ciudad de Ate, Lima. Ideal para viajeros que buscan cómodo y tranquilo.'},
 {'Título': 'Apartamento acogedor en Jirón El Refugio, La Molina',
  'Descripción': 'Diseñado para brindarte la máxima comodidad y ahorro energético. Ubicación privilegiada en La Molina, Lima.'},
 {'Título': 'Mini-departamento elegante en Ate, Lima',
  'Descripción': 'Ático moderno ubicado en el centro de la cosmopolita Lima. Espacioso, confortable y acorde con tus gustos. Ideal para vivir y disfrutar de la ciudad.'},
 {'Título': 'Casa en alquiler en Parque Asociación Huaycán, Lima',
  'Descripción': 'Elegida residencia en zona tranquila y verde de Huaycan, con acceso fácil a lugares turísticos.'},
 {'Título': 'Casa confortable en el corazón de Ate, Lima',
  'Descripción': 'Aprovecha esta oportunidad para vivir en una casa cómoda y bien ubicada en la ciudad de Ate, Lima. Está situado en un barrio tranquilo y accesible a diferentes zonas comerciales y recreativas.'},
 {'Título': 'Apto confortable y moderno en el corazón de Huaycán',
  'Descripción': 'Ofrecemos un apartamento moderno e iluminado situado en el corazón de la tranquila zona residencial de Huaycán, Ate. Inmueble cómodamente equipado con vistas a la zona verde.'},
 {'Título': 'Departamento lujoso en Ate, Lima',
  'Descripción': 'Elegía este moderno departamento bien ubicado en Ate, Lima Metropolitana. Disfruta de espacios amplios y comunes con excelentes instalaciones.'},
 {'Título': 'Departamento lujoso en Ate, Lima',
  'Descripción': 'Elegía este moderno departamento bien ubicado en Ate, Lima Metropolitana. Disfruta de espacios amplios y comunes con excelentes instalaciones.'},
 {'Título': 'Departamento moderno en Ate, Lima Metropolitana',
  'Descripción': 'Confortable departamento ubicado en el distrito de Ate, ofreciendo acceso fácil a las principales vías de la ciudad y servicios comunitarios.'},
 {'Título': 'Departamento moderno en Ate, Lima Metropolitana',
  'Descripción': 'Espacioso departamento de lujo en el distrito de Ate, ofrece una vida cómoda y práctica. Está situado en un edificio de estilo contemporáneo con acceso seguro.'},
 {'Título': 'Departamento moderno en Ate, Lima',

In [225]:
properties["title"] = [response["Título"] for response in responses]
properties["description"] = [response["Descripción"] for response in responses]
properties.head()

,distrito,departamento,geometry,address,property_type,operation_type,title,description
0,LIMA,LIMA,POINT (-77.00947 -12.05707),"Jirón Junín, San Cayetano, El Agustino, Lima, ...",casa,venta,"Casa moderna en Jirón Junín, San Cayetano",Venta de una hermosa y amplia casa ubicada en ...
1,LIMA,LIMA,POINT (-77.08194 -12.03984),"3300, Avenida Enrique Meiggs, Urbanización Ind...",departamento,venta,Departamento moderno en Urbanización Industria...,Ofrecemos un departamento bien ubicado en la u...
2,LIMA,LIMA,POINT (-77.0545 -12.04442),"Avenida República de Argentina, Mirones, Lima,...",local,alquiler,"Apartamento moderno en Mirones, Lima",Espacioso apartamento con vista a Avenida Repú...
3,LIMA,LIMA,POINT (-77.06685 -12.0466),"Luis Carranza, Mirones, Lima, Lima Metropolita...",departamento,venta,"Departamento lujoso en Mirones, Lima",Departamento elegante con vistas panorámicas d...
4,LIMA,LIMA,POINT (-77.03953 -12.06268),"Urbanización Cercado de Lima, Lima, Lima Metro...",local,venta,Casa moderna en exclusiva Urbanización Cercado...,Experimenta vivir en un espacio moderno y cómo...

In [226]:
# guardando
properties.to_file("data/generated_data/properties", driver="GeoJSON")

# Creating Prices

In [5]:
import random

In [2]:
properties = gpd.read_file("data/generated_data/properties")

In [ ]:
properties_w_price = properties.copy()
properties_w_price["price"] = properties_w_price.apply(
    lambda row: random.randint(300, 4000)
    if row["operation_type"] == "alquiler"
    else random.randint(30000, 300000),
    axis=1,
)

In [8]:
properties_w_price.to_file("data/generated_data/properties", driver="GeoJSON")

# Adding UUIDs

## users

In [9]:
import pandas as pd
import uuid

In [11]:
user_df = pd.read_csv("data/generated_data/users")

In [17]:
uuids = [str(uuid.uuid4()) for i in range(len(user_df))]

In [19]:
user_df["id"] = uuids

In [23]:
user_df.drop(columns="Unnamed: 0", inplace=True)

In [24]:
user_df.head()

,name,email,phone,role,password_hash,google_id,created_at,updated_at,id
0,Justin Cardenas,elizabethscott@example.net,870-216-4072,agent,1494958f642bb521f5debfba73f5f4ef,NaN,2025-06-17T16:20:17.189701,2025-06-17T16:20:17.189701,294d4ca0-927a-4ace-89c6-891e1152f9c1
1,Craig Coleman,ellissummer@example.net,001-626-731-3556x015,agent,d7fef1484628e4603253952469c902fb,NaN,2025-06-17T16:20:17.189701,2025-06-17T16:20:17.189701,a73af841-52c1-48c5-812a-e7e990562dc8
2,Cassandra Wright,ashley97@example.com,(351)366-9035x039,agent,9884171ecb4a502e111ba01b4467274e,NaN,2025-06-17T16:20:17.191745,2025-06-17T16:20:17.191745,82e8c70e-27ce-49fb-a89e-cb3940609051
3,Renee Miller,xavier01@example.net,6575078532,agent,744e0a6deef869bdeeef38b866afee5e,NaN,2025-06-17T16:20:17.192933,2025-06-17T16:20:17.192933,db09adc3-9f11-4ec6-894c-8e877f005e5f
4,Elizabeth Brooks,mary87@example.net,+1-630-760-1704,agent,a546aeb76c26feca0d0b99066395e6d7,NaN,2025-06-17T16:20:17.193930,2025-06-17T16:20:17.193930,1454fdde-3152-47a5-aef0-538a8f7067de

In [26]:
user_df.to_csv("data/generated_data/users.csv", index=False)

# properties

In [31]:
def random_user_id():
    index = random.randint(0, len(user_df) - 1)
    return user_df["id"][index]

In [37]:
properties_w_price.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 493 entries, 0 to 492
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   distrito        493 non-null    object
 1   departamento    493 non-null    object
 2   address         493 non-null    object
 3   property_type   493 non-null    object
 4   operation_type  493 non-null    object
 5   title           493 non-null    object
 6   description     493 non-null    object
 7   geometry        493 non-null    geometry
 8   price           493 non-null    int64
dtypes: geometry(1), int64(1), object(7)
memory usage: 34.8+ KB

In [40]:
properties_w_price["user_id"] = [
    random_user_id() for i in range(len(properties_w_price))
]

In [42]:
properties_w_price.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 493 entries, 0 to 492
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   distrito        493 non-null    object
 1   departamento    493 non-null    object
 2   address         493 non-null    object
 3   property_type   493 non-null    object
 4   operation_type  493 non-null    object
 5   title           493 non-null    object
 6   description     493 non-null    object
 7   geometry        493 non-null    geometry
 8   price           493 non-null    int64
 9   user_id         493 non-null    object
dtypes: geometry(1), int64(1), object(8)
memory usage: 38.6+ KB

In [47]:
# properties_w_price.drop(columns=['distrito', 'departamento'], inplace=True)
properties_w_price.rename(columns={"geometry": "geolocation"}, inplace=True)

In [51]:
properties_w_price["status"] = "available"

In [54]:
properties_w_price.to_file("data/generated_data/properties_final.geojson")

# Data Load DB Local

# Data Load DB Local

# users

In [55]:
from sqlalchemy import create_engine

In [56]:
engine = create_engine("postgresql+psycopg2://admin:admin123@localhost:5432/housy-db")

In [59]:
user_df.to_sql("users", engine, if_exists="append", index=False)

1000

# properties

In [68]:
properties_w_price.set_geometry("geolocation", inplace=True)
properties_w_price.to_postgis("properties", engine, if_exists="append", index=False)

# Data Load DB DEV

In [1]:
from sqlalchemy import create_engine
import os
import pandas as pd
import geopandas as gpd

In [2]:
db_user = os.environ["POSTGRESQL_DEV_USER"]
db_password = os.environ["POSTGRESQL_DEV_PASSWORD"]
db_name = os.environ["POSTGRESQL_DEV_DB"]
db_url = "housy-cluster.c0z0coi28tap.us-east-1.rds.amazonaws.com"

engine = create_engine(
    f"postgresql+psycopg2://{db_user}:{db_password}@{db_url}:5432/{db_name}"
)

## User table

In [3]:
user_df = pd.read_csv("data/generated_data/users.csv")
user_df.head(5)

,name,email,phone,role,password_hash,google_id,created_at,updated_at,id
0,Justin Cardenas,elizabethscott@example.net,870-216-4072,agent,1494958f642bb521f5debfba73f5f4ef,NaN,2025-06-17T16:20:17.189701,2025-06-17T16:20:17.189701,294d4ca0-927a-4ace-89c6-891e1152f9c1
1,Craig Coleman,ellissummer@example.net,001-626-731-3556x015,agent,d7fef1484628e4603253952469c902fb,NaN,2025-06-17T16:20:17.189701,2025-06-17T16:20:17.189701,a73af841-52c1-48c5-812a-e7e990562dc8
2,Cassandra Wright,ashley97@example.com,(351)366-9035x039,agent,9884171ecb4a502e111ba01b4467274e,NaN,2025-06-17T16:20:17.191745,2025-06-17T16:20:17.191745,82e8c70e-27ce-49fb-a89e-cb3940609051
3,Renee Miller,xavier01@example.net,6575078532,agent,744e0a6deef869bdeeef38b866afee5e,NaN,2025-06-17T16:20:17.192933,2025-06-17T16:20:17.192933,db09adc3-9f11-4ec6-894c-8e877f005e5f
4,Elizabeth Brooks,mary87@example.net,+1-630-760-1704,agent,a546aeb76c26feca0d0b99066395e6d7,NaN,2025-06-17T16:20:17.193930,2025-06-17T16:20:17.193930,1454fdde-3152-47a5-aef0-538a8f7067de

In [4]:
user_df.rename(
    columns={
        "password_hash": "password",
        "created_at": "createdAt",
        "updated_at": "updatedAt",
    },
    inplace=True,
)
user_df.drop(columns=["google_id"], inplace=True)

In [26]:
duplicated_mask = user_df.duplicated(subset="email")
user_df.loc[duplicated_mask, "email"] = "X" + user_df.loc[duplicated_mask, "email"]

In [27]:
user_df

,name,email,phone,role,password,createdAt,updatedAt,id
0,Justin Cardenas,elizabethscott@example.net,870-216-4072,agent,1494958f642bb521f5debfba73f5f4ef,2025-06-17T16:20:17.189701,2025-06-17T16:20:17.189701,294d4ca0-927a-4ace-89c6-891e1152f9c1
1,Craig Coleman,ellissummer@example.net,001-626-731-3556x015,agent,d7fef1484628e4603253952469c902fb,2025-06-17T16:20:17.189701,2025-06-17T16:20:17.189701,a73af841-52c1-48c5-812a-e7e990562dc8
2,Cassandra Wright,ashley97@example.com,(351)366-9035x039,agent,9884171ecb4a502e111ba01b4467274e,2025-06-17T16:20:17.191745,2025-06-17T16:20:17.191745,82e8c70e-27ce-49fb-a89e-cb3940609051
3,Renee Miller,xavier01@example.net,6575078532,agent,744e0a6deef869bdeeef38b866afee5e,2025-06-17T16:20:17.192933,2025-06-17T16:20:17.192933,db09adc3-9f11-4ec6-894c-8e877f005e5f
4,Elizabeth Brooks,mary87@example.net,+1-630-760-1704,agent,a546aeb76c26feca0d0b99066395e6d7,2025-06-17T16:20:17.193930,2025-06-17T16:20:17.193930,1454fdde-3152-47a5-aef0-538a8f7067de
...,...,...,...,...,...,...,...,...
995,Monica Johnson,jeremy62@example.org,531-802-3784x442,agent,5655bfaf98553c5470d57aba9c2cd21b,2025-06-17T16:20:18.066229,2025-06-17T16:20:18.066229,c279805e-2991-41c3-9167-5e27560ca6aa
996,Barbara Livingston,vdeleon@example.org,859-372-5851x72371,agent,3a23e354b31cabbdcb2d063bea1e7614,2025-06-17T16:20:18.067232,2025-06-17T16:20:18.067232,23827096-2f5f-48b9-bb62-d99b0d6d011b
997,Janet Wade,christinahogan@example.com,(933)610-4869x7916,agent,d2873b9cf873884bf31be1de5f5160a8,2025-06-17T16:20:18.068229,2025-06-17T16:20:18.068229,912f2e7d-3cf0-40c9-8f69-b43c85246ae0
998,Bonnie Casey,lhess@example.com,723-534-7100x00189,agent,8d59e42c4e119d3fb839f81ddb9c2159,2025-06-17T16:20:18.069229,2025-06-17T16:20:18.069229,e5601ab4-2590-40bb-a749-4b56f37885b0
999,Michelle Gilbert,austinmorris@example.org,9154997532,agent,7ac64929dc55f4096a255b4026c8614d,2025-06-17T16:20:18.070232,2025-06-17T16:20:18.070232,d942b7fa-eb3f-4f0f-8cc2-f10c6541ee67

In [28]:
user_df.to_sql(
    "user",
    engine,
    if_exists="append",
    index=False,
)

1000

## Properties table

In [29]:
properties = gpd.read_file("data/generated_data/properties_final.geojson")

In [30]:
properties.rename(columns={"geometry": "geolocation"}, inplace=True)
properties.set_geometry("geolocation", inplace=True)

In [23]:
properties.to_postgis("properties", engine, if_exists="append", index=False)

### adaptation for 'property schema'

In [32]:
property_df = pd.DataFrame(properties)

In [ ]:
property_df.head()

,address,property_type,operation_type,title,description,price,user_id,status,geolocation
0,"Jirón Junín, San Cayetano, El Agustino, Lima, ...",casa,venta,"Casa moderna en Jirón Junín, San Cayetano",Venta de una hermosa y amplia casa ubicada en ...,218111,1250f7df-d886-45e8-91ae-edcd3426c599,available,POINT (-77.00947 -12.05707)
1,"3300, Avenida Enrique Meiggs, Urbanización Ind...",departamento,venta,Departamento moderno en Urbanización Industria...,Ofrecemos un departamento bien ubicado en la u...,134349,5f2f7fdd-c2de-452d-b433-512cb31ea359,available,POINT (-77.08194 -12.03984)
2,"Avenida República de Argentina, Mirones, Lima,...",local,alquiler,"Apartamento moderno en Mirones, Lima",Espacioso apartamento con vista a Avenida Repú...,3400,9449ebae-1b51-40bc-a95b-76c57cd5102b,available,POINT (-77.0545 -12.04442)
3,"Luis Carranza, Mirones, Lima, Lima Metropolita...",departamento,venta,"Departamento lujoso en Mirones, Lima",Departamento elegante con vistas panorámicas d...,227185,851dd10d-7f2a-4084-804f-f2d3a73eaa5e,available,POINT (-77.06685 -12.0466)
4,"Urbanización Cercado de Lima, Lima, Lima Metro...",local,venta,Casa moderna en exclusiva Urbanización Cercado...,Experimenta vivir en un espacio moderno y cómo...,248189,52ac5449-d5e1-4d8e-b9fa-98a2b796ea1d,available,POINT (-77.03953 -12.06268)
...,...,...,...,...,...,...,...,...,...
488,"Urbanización Cooviecma, Santiago de Surco, Lim...",casa,alquiler,"Casa confortable en Urbanización Cooviecma, Sa...",Alquila una moderna y acogedora casa en la pre...,2367,11f50cb6-5c46-4924-872e-9265e6cc0307,available,POINT (-77.00642 -12.1413)
489,"Avenida Paseo de la República, Urbanización Sa...",mini-departamento,alquiler,"Mini-departamento lujoso en San Mateo, Santiag...",Alquila un mini-departamento moderno y bien de...,3301,d8a0534c-e384-4266-a5b0-00a1820ff18d,available,POINT (-76.99853 -12.14501)
490,"Calle Teniente José Melitón Rodríguez, Urbaniz...",casa,alquiler,"Casa alquiler en Urbanización Cooviecma, Santi...",Casa disponible para alquilar en la tranquila ...,3679,f5993568-b95b-4e0b-ba5c-42c6531f331a,available,POINT (-77.00842 -12.1445)
491,"Pasaje Augusto López Rodríguez, Viñedos de Sur...",mini-departamento,alquiler,Mini-departamento moderno en Viñedos de Surco,"Ático moderno en un tranquilo Pasaje, cerca de...",968,6afde45d-053e-43e6-8beb-74f0142bf4d0,available,POINT (-76.98765 -12.1632)
492,"Will Market Valle Hermoso, 176, Los Laureles, ...",departamento,alquiler,Departamento envalentonado de Los Laureles,"Debajo del sol radiante de San Demetrio, se en...",3615,da5cccd1-afb5-4533-a544-132ceb4ec381,available,POINT (-76.97453 -12.1259)

In [36]:
property_df.drop(columns=["property_type", "operation_type"], inplace=True)

In [37]:
property_df.head()

,address,title,description,price,user_id,status,geolocation
0,"Jirón Junín, San Cayetano, El Agustino, Lima, ...","Casa moderna en Jirón Junín, San Cayetano",Venta de una hermosa y amplia casa ubicada en ...,218111,1250f7df-d886-45e8-91ae-edcd3426c599,available,POINT (-77.00947 -12.05707)
1,"3300, Avenida Enrique Meiggs, Urbanización Ind...",Departamento moderno en Urbanización Industria...,Ofrecemos un departamento bien ubicado en la u...,134349,5f2f7fdd-c2de-452d-b433-512cb31ea359,available,POINT (-77.08194 -12.03984)
2,"Avenida República de Argentina, Mirones, Lima,...","Apartamento moderno en Mirones, Lima",Espacioso apartamento con vista a Avenida Repú...,3400,9449ebae-1b51-40bc-a95b-76c57cd5102b,available,POINT (-77.0545 -12.04442)
3,"Luis Carranza, Mirones, Lima, Lima Metropolita...","Departamento lujoso en Mirones, Lima",Departamento elegante con vistas panorámicas d...,227185,851dd10d-7f2a-4084-804f-f2d3a73eaa5e,available,POINT (-77.06685 -12.0466)
4,"Urbanización Cercado de Lima, Lima, Lima Metro...",Casa moderna en exclusiva Urbanización Cercado...,Experimenta vivir en un espacio moderno y cómo...,248189,52ac5449-d5e1-4d8e-b9fa-98a2b796ea1d,available,POINT (-77.03953 -12.06268)

In [38]:
property_df.rename(
    columns={
        "address": "location",
        "created_at": "createdAt",
        "updated_at": "updatedAt",
    },
    inplace=True,
)

In [39]:
property_df.head()

,location,title,description,price,user_id,status,geolocation
0,"Jirón Junín, San Cayetano, El Agustino, Lima, ...","Casa moderna en Jirón Junín, San Cayetano",Venta de una hermosa y amplia casa ubicada en ...,218111,1250f7df-d886-45e8-91ae-edcd3426c599,available,POINT (-77.00947 -12.05707)
1,"3300, Avenida Enrique Meiggs, Urbanización Ind...",Departamento moderno en Urbanización Industria...,Ofrecemos un departamento bien ubicado en la u...,134349,5f2f7fdd-c2de-452d-b433-512cb31ea359,available,POINT (-77.08194 -12.03984)
2,"Avenida República de Argentina, Mirones, Lima,...","Apartamento moderno en Mirones, Lima",Espacioso apartamento con vista a Avenida Repú...,3400,9449ebae-1b51-40bc-a95b-76c57cd5102b,available,POINT (-77.0545 -12.04442)
3,"Luis Carranza, Mirones, Lima, Lima Metropolita...","Departamento lujoso en Mirones, Lima",Departamento elegante con vistas panorámicas d...,227185,851dd10d-7f2a-4084-804f-f2d3a73eaa5e,available,POINT (-77.06685 -12.0466)
4,"Urbanización Cercado de Lima, Lima, Lima Metro...",Casa moderna en exclusiva Urbanización Cercado...,Experimenta vivir en un espacio moderno y cómo...,248189,52ac5449-d5e1-4d8e-b9fa-98a2b796ea1d,available,POINT (-77.03953 -12.06268)

In [40]:
property_df.drop(columns=["geolocation"], inplace=True)

In [41]:
from random import randint

In [42]:
property_df["bedrooms"] = randint(1, 3)
property_df["bathrooms"] = randint(1, 3)

In [52]:
property_df["bedrooms"] = property_df["bedrooms"].apply(randint, b=3)
property_df["bathrooms"] = property_df["bathrooms"].apply(randint, b=3)

In [53]:
property_df

,location,title,description,price,user_id,status,bedrooms,bathrooms
0,"Jirón Junín, San Cayetano, El Agustino, Lima, ...","Casa moderna en Jirón Junín, San Cayetano",Venta de una hermosa y amplia casa ubicada en ...,218111,1250f7df-d886-45e8-91ae-edcd3426c599,available,3,3
1,"3300, Avenida Enrique Meiggs, Urbanización Ind...",Departamento moderno en Urbanización Industria...,Ofrecemos un departamento bien ubicado en la u...,134349,5f2f7fdd-c2de-452d-b433-512cb31ea359,available,1,2
2,"Avenida República de Argentina, Mirones, Lima,...","Apartamento moderno en Mirones, Lima",Espacioso apartamento con vista a Avenida Repú...,3400,9449ebae-1b51-40bc-a95b-76c57cd5102b,available,3,2
3,"Luis Carranza, Mirones, Lima, Lima Metropolita...","Departamento lujoso en Mirones, Lima",Departamento elegante con vistas panorámicas d...,227185,851dd10d-7f2a-4084-804f-f2d3a73eaa5e,available,1,2
4,"Urbanización Cercado de Lima, Lima, Lima Metro...",Casa moderna en exclusiva Urbanización Cercado...,Experimenta vivir en un espacio moderno y cómo...,248189,52ac5449-d5e1-4d8e-b9fa-98a2b796ea1d,available,1,3
...,...,...,...,...,...,...,...,...
488,"Urbanización Cooviecma, Santiago de Surco, Lim...","Casa confortable en Urbanización Cooviecma, Sa...",Alquila una moderna y acogedora casa en la pre...,2367,11f50cb6-5c46-4924-872e-9265e6cc0307,available,1,3
489,"Avenida Paseo de la República, Urbanización Sa...","Mini-departamento lujoso en San Mateo, Santiag...",Alquila un mini-departamento moderno y bien de...,3301,d8a0534c-e384-4266-a5b0-00a1820ff18d,available,2,2
490,"Calle Teniente José Melitón Rodríguez, Urbaniz...","Casa alquiler en Urbanización Cooviecma, Santi...",Casa disponible para alquilar en la tranquila ...,3679,f5993568-b95b-4e0b-ba5c-42c6531f331a,available,1,3
491,"Pasaje Augusto López Rodríguez, Viñedos de Sur...",Mini-departamento moderno en Viñedos de Surco,"Ático moderno en un tranquilo Pasaje, cerca de...",968,6afde45d-053e-43e6-8beb-74f0142bf4d0,available,2,2
492,"Will Market Valle Hermoso, 176, Los Laureles, ...",Departamento envalentonado de Los Laureles,"Debajo del sol radiante de San Demetrio, se en...",3615,da5cccd1-afb5-4533-a544-132ceb4ec381,available,3,2

In [55]:
property_df.rename(columns={"user_id": "userId"}, inplace=True)

In [56]:
property_df.to_sql(
    "property",
    engine,
    if_exists="append",
    index=False,
)

493